apiVersion: v1
kind: Service
metadata:
  labels:
    service: api-frontend
  name: api-frontend
spec:
  ports:
    - name: "http"
      port: 80
      targetPort: 80
  selector:
    service: api-frontend
